### ISSUE TITLE
WifiSense/Defender: Unable to modify Windows Defender Spynet key

### ISSUE THREAD

**Issue by xtra7973** [10se1ucgo/DisableWinTracking#138] opened 2015-12-31 13:29 UTC
**INFORMATION:**

* Windows 10 Pro 
* Architecture 64bit 
* Options used: Disabled all tracking

**LOG:**

```python
DiagTrack Log: Succesfully cleared and locked.
Services: dmwappushsvc key successfully modified.
Services: DiagTrack key successfully modified.
Telemetry: AllowTelemetry key successfully modified.
Domain block: Domains succesfully appended.
Extra domain block: Domains succesfully appended.
IP Blocking: Succesfully blocked.
WifiSense/Defender: Unable to modify Windows Defender Spynet key.
WifiSense/Defender: Unable to modify Windows Defender Sample Submission key.
WifiSense/Defender: WifiSense Open-ness key successfully modified.
WifiSense/Defender: WifiSense Credential Share key successfully modified.
WifiSense/Defender: Windows Defender Delivery Optimization Download key successfully modified.
OneDrive: ListPin key successfully modified.
OneDrive: FileSync key successfully modified.
OneDrive: Succesfully uninstalled.
Done. It's recommended that you reboot as soon as possible for the full effect.
If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by MrSquib** [comment] 2016-01-06 23:34
Same thing happened to me.

**Comment by 10se1ucgo** [comment] 2016-01-10 00:50
Duplicate of #88

**Closed by 10se1ucgo** 2016-01-10 00:50 UTC
Labels: duplicate
