### ISSUE TITLE
Skype connectivity issues

### ISSUE THREAD

**Issue by Sylencer90** [10se1ucgo/DisableWinTracking#99] opened 2015-10-06 16:11 UTC
Some messages doesn't get delivered here. But i already removed (maybe) all skype domains from my Hosts file. What else could that cause? It's not an skype issue tho, either some blocked domains or my network. Seeing like 1/3 of my contacts online but some are online but i see them as offline, tried reconnecting and relogging + router restart. Weird.

**Comment by TheDrink** [comment] 2015-10-06 16:33
This has been commented on many times before... Will further elaborate when not on mobile.

**Comment by 10se1ucgo** [comment] 2015-10-08 14:14
Still can't reproduce.

**Comment by jmdbox** [comment] 2015-10-10 19:41
I can confirm, basically Skype becomes all bugged out, with the host file entries.   Clear out the hosts file, reboot, and then skype works again for me.  For now i just apply all the settings then just clear the hosts file.   THis on the current version of skype of course, not running any 3rd party firewalls or anything, just basic antivirus.

**Comment by Ruined1** [comment] 2015-10-10 20:37
@jmdbox
>I can confirm, basically Skype becomes all bugged out, with the host file entries.

please define "bugged out"

**Comment by jmdbox** [comment] 2015-10-10 22:59
Well basically, skype logs in, but doesn't load any contacts as online, then maybe it does after a long while but not always (and i know they're online cause i am texting them on cell phone), and then someone calls me, i can hear their speech but they cant hear me or vice-versa, also cannot type any text messages to anyone or recieve any.   Really strange like i can make a call, but can't answer one and when a call does get through, again cannot text ever, and their picture shows as black and the call comes up as something like "missing group" or something werid like that.   Best i can explain it, it just kind of like is all stuck in limbo.   Again, clearing out the specific entries in the HOSTS file that DisableWinTracking adds, completely fixes it and skype is back to being smooth as silk, did this like 3 or 4 times and it's definitely something with these hosts file entries.

**Comment by Ruined1** [comment] 2015-10-11 00:52
@jmdbox your explanation is perfect, and that sounds EXACTLY like a server issue, so if it worked perfect with hosts gone and then came back when you used disable win tracking, then yes likely we need to come over the hosts, on mobile right now will reply again shortly with more info and/or a fix

**Comment by Ruined1** [comment] 2015-10-11 06:18
@jmdbox open your HOSTS file in notepad (MAKE SURE NOTEPAD IS RUN AS ADMINISTRATOR!) and try removing the following 1 by 1 after running DisableWinTracking again.
>'ui.skype.com', 'pricelist.skype.com', 'apps.skype.com',

I'd do it myself but I dont use Skype, I think it's horrible and there are plenty of alternatives to Micro$oft programs

**Comment by jmdbox** [comment] 2015-10-11 15:36
@Ruined1: yeah i tried that too, removing any entries with "skype" in it, still the problems persisted.   Ok i guess it's up to me, i'll try to pin down which entries are causing it, going to be a pain but i really want to have this working with skype.   Not that i'm a big fan of microsoft programs, i generally try to use 3rd party stuff but all my contacts are on skype and well that's that. 

I will post here any success that i have in figuring out which entries are the problem.

**Comment by jmdbox** [comment] 2015-10-11 16:23
I narrowed it down, it is this entry that is messing up skype:

0.0.0.0 s.gateway.messenger.live.com

Removed this one, all is good again.  Hope this helps.

**Comment by Ruined1** [comment] 2015-10-11 23:00
@jmdbox Fantastic! And thank you for your contribution :stuck_out_tongue_winking_eye: 

I'll implement something to reconcile this.

**Comment by Ruined1** [comment] 2015-10-11 23:53
Fixed in #103

**Closed by Ruined1** 2015-10-11 23:53 UTC
Labels: cannot reproduce
