### ISSUE TITLE
3.0.1 / SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Quest33** [10se1ucgo/DisableWinTracking#230] opened 2016-09-06 05:09 UTC
**INFORMATION:**
download > decompress > right-click on DisableWinTracking.exe > Run as administrator > ERROR!
- Windows Edition (Home/Pro/Enterprise): Enterprise
- Architecture (32bit/64bit): 64
- Options used: NONE

**LOG:**
07:01:15 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
07:01:15 INFO: ('Windows', 'XXXXXX', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
07:01:15 INFO: DisableWinTracking version 3.0.1
07:01:16 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 440, in <module>
  File "dwt_about.py", line 170, in update_check
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

```
```

**Comment by ImDevinC** [comment] 2016-12-07 19:30
Duplicate of #164 can probably be closed and discussion brought there

**Comment by KulaGGin** [comment] 2017-04-16 13:33
In my case problem was that in the path to the program I had Cyrillic characters, it was _H:\Интернет\dwt-3.0.1-cp27-win_x86\DisableWinTracking.exe_. I cut and pasted folder to the root directory of the drive _H:\dwt-3.0.1-cp27-win_x86\_ and now program works.

**Comment by Ruined1** [comment] 2017-04-24 10:40
Fixed. Merged. Will be included in the next release if you are not compiling it yourself.

**Closed by Ruined1** 2017-04-24 10:40 UTC
