### ISSUE TITLE
IP's/Domains are not added to hosts file - error log attached

### ISSUE THREAD

**Issue by th3r3isnospoon** [10se1ucgo/DisableWinTracking#67] opened 2015-09-03 03:52 UTC
Hello, the last rev prior to the latest release would work correctly (as in edit the host file) however the newer version does not. This is a win 10 64-BIT machine.  Thanks for working on a cool tool :)  Here are the errors:

```python
23:46:44 ERROR: Registry: Unable to modify Service dmwappushsvc key.
Traceback (most recent call last):
  File "<string>", line 474, in modifyregistry
WindowsError: [Error 2] The system cannot find the file specified

23:46:44 ERROR: Registry: Unable to modify Service DiagTrack key.
Traceback (most recent call last):
  File "<string>", line 474, in modifyregistry
WindowsError: [Error 2] The system cannot find the file specified

23:46:44 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

23:46:44 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

23:46:44 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

23:46:44 ERROR: DiagTrack Log: Unable to clear/lock
Traceback (most recent call last):
  File "<string>", line 339, in cleardiagtracklog
IOError: [Errno 13] Permission denied: 'C:\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack-Listener.etl'
```

**Comment by 10se1ucgo** [comment] 2015-09-03 03:59
Not near a computer but I will try to fix it tomorrow morning.

**Comment by Ruined1** [comment] 2015-09-03 06:04
Ran into same issue with WD/WFS registry keys and onedrive filesync, also not available for troubleshooting at the moment.

**Comment by 10se1ucgo** [comment] 2015-09-03 14:09
Hmm, I'm not seeming to have this issue. Can anyone else try? Gonna put a cannot reproduce tag for now.

**Comment by Ruined1** [comment] 2015-09-03 16:45
@th3r3isnospoon Are you running a cracked (non-paid) version of Windows 10? We're not microsoft, we don't care what you do, but it's an important question because tracking related services might already be disabled in those for obvious reasons...

**Comment by th3r3isnospoon** [comment] 2015-09-03 16:52
@Ruined1 No sir.  It is a legitimate copy of Windows 10.  I was thinking about the errors though.  Would those errors pop up if I had run a previous version of this program?  I did run the old version and press revert, then I ran the newer version of this program and those are the errors that came back.  The latest rev would not add the IP's/Domain's into the hosts file, but the older version prior to this release worked.  I double checked and when I run the older version with elevated privileges it successfully edits the host file.

**Comment by Ruined1** [comment] 2015-09-03 17:08
These two lines are correct, as you probably deleted the services with a previous revision, so they don't exist to modify:
```
23:46:44 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

23:46:44 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')
```

I'm looking into the rest.

**Comment by th3r3isnospoon** [comment] 2015-09-03 17:09
@Ruined1 That would make sense, I did delete them with the previous revision.

**Comment by 10se1ucgo** [comment] 2015-09-04 00:57
@Ruined1 all of these error messages make sense. Except for the registry key error, I'll look into that later. As for the DiagTrack log, it makes sense because Python can't access the logger once it's cleared and locked because system has access denied to it, only the user himself can modify it.

**Comment by Ruined1** [comment] 2015-09-04 07:10
@10se1ucgo 

I Ran the latest commit, with all checks and DISABLE services, on a test machine with a brand new Windows 10 clean install.

I hope this is useful to you, as I can now easy provide it in the future from a clean install every time.

Console Output:
* Registry: Unable to modify Service dmwappushsvc key.
* Registry: Service DiagTrack key successfully modified.
* Services: dmwappushsvc unable to be stopped.
* Services: Diagnostics Tracking Service successfully stopped.
* Services: Diagnostics Tracking Service unable to be stopped.
* DiagTrack Log: Succesfully cleared and locked.
* Done. It's recommended that you reboot as soon as possible for the full effect.
* If any errors were found, please make a GitHub ticket with the contents of DisableWinTracking.log

DisableWinTracking.log
* Traceback (most recent call last):
  * File "E:\CUSTOM~2\DISABL~1\\DisableWinTracking-WIP.py", line 187, in goprivate
    modifytelemetryregs(telemetryval="0")
  * File "E:\CUSTOM~2\DISABL~1\\DisableWinTracking-WIP.py", line 376, in modifytelemetryregs
    modifyregistry(regdict=telemetrydict, bit=32)
  * File "E:\CUSTOM~2\DISABL~1\\DisableWinTracking-WIP.py", line 476, in modifyregistry
    _winreg.SetValueEx(modreg, registry[2], 0, registry[3], registry[4])
* ValueError: Could not convert the data to the specified type.```

**Comment by Ruined1** [comment] 2015-09-04 07:36
Latest test on clean install 64-bit Win 10 shows aces:
* Services: Diagnostics Tracking Service successfully stopped.
* Services: Diagnostics Tracking Service unable to be stopped.
* DiagTrack Log: Succesfully cleared and locked.
* Done. It's recommended that you reboot as soon as possible for the full effect.
* If any errors were found, please make a GitHub ticket with the contents of DisableWinTracking.log

Marking fixed and closing.

**Comment by th3r3isnospoon** [comment] 2015-09-04 18:36
Awesome thanks @10se1ucgo @Ruined1 !

**Comment by 10se1ucgo** [comment] 2015-09-04 20:03
```
File "E:\CUSTOM~2\DISABL~1\DisableWinTracking-WIP.py", line 376, in modifytelemetryregs modifyregistry(regdict=telemetrydict, bit=32) Why are we calling 32bit on a 64bit system?
```

Because the Telemetry registry things isn't a 64 bit regkey AFAIK. I'll look into this further.

**Comment by skibbipl** [comment] 2015-09-05 22:50
I'm also having issues with latest version. After running it my hosts files and firewall rules were deleted. And there are no errors in the log. However the old version has following enitries in the log:
`Domains successfully appended to HOSTS file.`
`IPs succesfully blocked.`
The new version does not display any of those.

**Comment by 10se1ucgo** [comment] 2015-09-05 22:52
The new version did not change anything in regards to IP blocking, so it's def not a problem on our side.

**Comment by skibbipl** [comment] 2015-09-05 22:56
Old version updates hosts file and firewall rules - new doesn't. There is def a problem somewhere. Unfortunately new version does not log anything suspicious.

**Comment by 10se1ucgo** [comment] 2015-09-05 23:01
The new version does log things. DisableWinTracking.log.

Also, I just showed to you that it works for me. Something is up on your side. Mind giving a bit more information, e.g. Windows version, 64-bit/32-bit, Windows edition?

**Comment by 10se1ucgo** [comment] 2015-09-05 23:04
@skibbipl try this
https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v2.4.1

**Comment by skibbipl** [comment] 2015-09-05 23:13
I use 64-bit polish windows. But I think I found the problem. If I select Telemetry + Block tracking domains hosts file is nulled. If I select only block... it works fine. Firewall rules are created correctly.

**Comment by 10se1ucgo** [comment] 2015-09-05 23:14
Really? That's odd. I'll look into this. Going to re-open for now.

**Comment by Ruined1** [comment] 2015-09-06 09:53
Here's my test, making sure the compiled EXE is the same as the source code I'm running.
- On my Laptop 64 bit win10
    - running through the interpreter from the source code, the HOSTS is modified
    - running from the compiled EXE, the HOSTS is CLEARED, but not re-modified
    - close and reopened  the compiled EXE, the HOSTS is still blank (default HOSTS file)
    - running through the interpreter from the source code, HOSTS is still blank (default HOSTS file)
- On my Testbench 64 bit win10
    - running from the compiled EXE, the HOSTS is CLEARED, but not re-modified

Both OS's were installed from the same media.

**There is something very strange going on here, and I don't like it...**

 Maybe I'm too tired to see something obvious...

**Comment by 10se1ucgo** [comment] 2015-09-07 20:26
I may have been able to fix it with the latest commit, we'll see.

**Comment by 10se1ucgo** [comment] 2015-09-07 20:28
@Ruined1 It works!!!

```python
Services: dmwappushsvc key successfully modified.
Services: DiagTrack key successfully modified.
Services: dmwappushsvc unable to be stopped.
Services: Diagnostics Tracking Service unable to be stopped.
Services: Diagnostics Tracking Service unable to be stopped.
DiagTrack Log: Succesfully cleared and locked.
Telemetry: AllowTelemetry key successfully modified.
Domain block: Domains succesfully appended.
Extra domain block: Domains succesfully appended.
IP Blocking: Succesfully blocked.
WifiSense/Defender: Unable to modify Windows Defender Spynet key.
WifiSense/Defender: Unable to modify Windows Defender Sample Submission key.
WifiSense/Defender: WifiSense Open-ness key successfully modified.
WifiSense/Defender: WifiSense Credential Share key successfully modified.
WifiSense/Defender: Windows Defender Delivery Optimization Download key successfully modified.
OneDrive: : ListPin key successfully modified.
OneDrive: : FileSync key successfully modified.
OneDrive: Succesfully uninstalled.
Done. It's recommended that you reboot as soon as possible for the full effect.
If any errors were found, please make a GitHub ticket with the contents of DisableWinTracking.log
```

**Closed by 10se1ucgo** 2015-09-07 20:28 UTC
Labels: bug

**Comment by Ruined1** [comment] 2015-09-07 21:58
@10se1ucgo Eureka! I'm going to check this on a test bench with a clean install and manually check all the keys/settings/etc to make sure, but I think it's good!
