### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lunatic0696** [10se1ucgo/DisableWinTracking#310] opened 2017-04-24 02:02 UTC
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
23:00:20 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
23:00:20 INFO: ('Windows', 'Lunatic', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
23:00:20 INFO: DisableWinTracking version 3.0.1
23:00:48 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
23:00:48 CRITICAL: DiagTrack: Error output:

23:00:48 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 109, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'O servi\xe7o especificado foi marcado para ser exclu\xeddo.')
23:00:48 INFO: Registry: Successfully modified dmwappushsvc key.
23:00:48 INFO: Registry: Successfully modified DiagTrack key.
23:00:48 INFO: Registry: Successfully modified AllowTelemetry key.
23:00:48 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:00:48 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
```

**Comment by Ruined1** [comment] 2017-04-26 04:31
This is likely due to a change on microsofts end, bet they upped the permissions for touching the logger output. Noted and will invesitgate.

**Comment by Ruined1** [comment] 2017-04-26 18:18
The first error is reproducable, but I'm going to call it a duplicate of #312 since there are other errors bundled with that need addressed as well. I'll fixx that asap.

**However**, I just ran it on a clean copy of windows 10 pro x64 using the latest release and got this:
`13:59:31 INFO: Services: Succesfully removed service 'DiagTrack'`
So I am unable to reproduce that error, and others have not reported it being an issue (#312 didn't have that issue either). Are you running a pirated copy of Windows? If so, it's likely already removed. I will go ahead and close this issue, create a new issue for anything else. Thanks for your contribution! It's appreciated!

**Closed by Ruined1** 2017-04-26 18:18 UTC
