### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by CryptXor** [10se1ucgo/DisableWinTracking#49] opened 2015-08-27 13:56 UTC
Please be noted that disabling the trackers using the host file will cause issues with Skype. Symptoms are observable if your client states in a group chat that "instant messaging is not available. <something about updating skype bla bla bla".

To fix look for the *.skype entries in the hosts file and the *message.live entry. Commenting/removing them will fix the problem :)

**Comment by 10se1ucgo** [comment] 2015-08-27 17:05
I'm not having this issue

**Comment by thekot** [comment] 2015-08-27 19:05
Today I had some weird Skype behavior. It just felt like Skype can't synchronize to some servers. I've tried to reproduce the issue on virtual box with and without hosts blocked. I removed blocked hosts and it did helped, Skype goes normal. Then I rewind virtual machine back to it's original state with hosts blocked and the issue seems gone. Maybe one of main Skype servers was down and it tried to access another which was blocked.

**Comment by StinkyMojo** [comment] 2015-08-28 00:48
The OP is correct, I have reproduced this issue twice on two different machines now. I was able to install Skype only by reverting Block tracking domains, Block even more tracking domains, and Block tracking IP addresses.

**Comment by 10se1ucgo** [comment] 2015-08-28 01:07
Like I said, I'm not having issues and I can't reproduce it.

![unable to reproduce](http://i.imgur.com/Xg5gi8d.png)

I'll re-open this for now.

**Comment by 10se1ucgo** [comment] 2015-08-28 01:14
I've moved the skype domains from the normal list to the extra domain list for now, until I figure out which domain is causing the issue for you guys. Unfortunately I can't reproduce so this may take some time.

9d603d77cb38bc0c0c3e639131be79780b5a7658

**Comment by StinkyMojo** [comment] 2015-08-28 01:15
After I successfully re-ran your awesome app a few moments ago (thanks, by the way!), Skype has been working as it should. It seems as if you have to install Skype first blocking any domains.

**Comment by 10se1ucgo** [comment] 2015-08-28 02:33
It seems ui.skype.com may be connected to updates, I'll remove that as soon as I confirm it.

**Comment by CryptXor** [comment] 2015-08-28 05:56
@10se1ucgo s.gateway.messenger.live.com seems to be the major culprit. I just commented out all the *.skype.com ones. It seems to affect group-chats mostly :)

@StinkyMojo Nope. I tried and since it cannot contact the peering servers it breaks down rather quickly.

**Comment by thekot** [comment] 2015-08-28 12:02
I did some more testing about the issue.

When ui.skype.com is blocked I wasn't able to install (with web installer) nor update Skype.

I do have a snapshot of virtual pc with clean hosts file and without Skype installed. When I do clean Skype install with s.gateway.messenger.live.com blocked I cannot see any group chats that I had created before. Seems group chats just not being synchronized. But I'm able to create and use new group chats.

**Comment by 10se1ucgo** [comment] 2015-08-28 19:26
Fixed in 168022e0062641347b4a10c2e1dbf7ca640bbfe2

Download v2.3 here: https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v2.3

Run the program and press "Fix Skype/Mail"

**Closed by 10se1ucgo** 2015-08-28 19:26 UTC
Labels: bug

**Comment by Esux** [comment] 2015-11-08 16:13
First off I apologize for posting in what seems like a resolved bug, but using a fresh windows install (Windows 10 Enterprise LTSB) and version 2.5.1 of this program it still breaks skype and I do not see the 'Fix Skype/Mail' option. Either I'm blind or it was removed because the bug was deemed to be resolved?

**Comment by 10se1ucgo** [comment] 2015-11-08 16:39
It was removed because the extra hosts block was meant for the paranoid, and that they should understand the side effects of it. To fix it, just use an older version that still has it.
